const enLang = [
    [
        { code: 'Key_Backtick', name: '`', shiftName: '~', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_1', name: '1', shiftName: '!', class: 'shortkey',  property: 'printable', location: 0, }, 
        { code: 'Key_2', name: '2', shiftName: '@', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_3', name: '3', shiftName: '#', class: 'shortkey',  property: 'printable', key: '3', }, 
        { code: 'Key_4', name: '4', shiftName: '$', class: 'shortkey',  property: 'printable', unicode: '④', }, 
        { code: 'Key_5', name: '5', shiftName: '%', class: 'shortkey',  property: 'printable', keyCode: 53, unicode: '⑤'}, 
        { code: 'Key_6', name: '6', shiftName: '^', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_7', name: '7', shiftName: '&', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_8', name: '8', shiftName: '*', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_9', name: '9', shiftName: '(', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_0', name: '0', shiftName: ')', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Minus', name: '-', shiftName: '_', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Equal', name: '=', shiftName: '+', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Backspace', name: 'Backspace', shiftName: 'Backspace', class: 'longkey large', }, 
    ],
    [
        { code: 'Key_Tab', name: 'Tab', shiftName: 'Tab', class: 'longkey small', }, 
        { code: 'Key_Q', name: 'q', shiftName: 'Q', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_W', name: 'w', shiftName: 'W', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_E', name: 'e', shiftName: 'E', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_R', name: 'r', shiftName: 'R', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_T', name: 't', shiftName: 'T', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Y', name: 'y', shiftName: 'Y', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_U', name: 'u', shiftName: 'U', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_I', name: 'i', shiftName: 'I', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_O', name: 'o', shiftName: 'O', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_P', name: 'p', shiftName: 'P', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Bracket_Left', name: '[', shiftName: '{', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Bracket_Right', name: ']', shiftName: '}', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Backslash', name: '\\', shiftName: '|', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Delete', name: 'Del', shiftName: 'Del', class: 'longkey small', },
    ],
    [
        { code: 'Key_Caps', name: 'Caps', shiftName: 'Caps', class: 'longkey small', }, 
        { code: 'Key_A', name: 'a', shiftName: 'A', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_S', name: 's', shiftName: 'S', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_D', name: 'd', shiftName: 'D', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_F', name: 'f', shiftName: 'F', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_G', name: 'g', shiftName: 'G', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_H', name: 'h', shiftName: 'H', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_J', name: 'j', shiftName: 'J', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_K', name: 'k', shiftName: 'K', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_L', name: 'l', shiftName: 'L', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Semicolon', name: ';', shiftName: ':', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Quote', name: '\'', shiftName: '\"', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Enter', name: 'Enter', shiftName: 'Enter', class: 'longkey large', },
    ],
    [
        { code: 'Key_Shift_Left', name: 'Shift', shiftName: 'Shift', class: 'longkey medium', }, 
        { code: 'Key_Z', name: 'z', shiftName: 'Z', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_X', name: 'x', shiftName: 'X', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_C', name: 'c', shiftName: 'C', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_V', name: 'v', shiftName: 'V', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_B', name: 'b', shiftName: 'B', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_N', name: 'n', shiftName: 'N', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_M', name: 'm', shiftName: 'M', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Comma', name: ',', shiftName: '<', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Dot', name: '.', shiftName: '>', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Slash', name: '/', shiftName: '?', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Up', name: '▲', shiftName: '▲', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Shift_Right', name: 'Shift', shiftName: 'Shift', class: 'longkey medium', }, 
    ],
    [
        { code: 'Key_Ctrl_Left', name: 'Ctrl', shiftName: 'Ctrl', class: 'longkey small', }, 
        { code: 'Key_Win', name: 'Win', shiftName: 'Win', class: 'longkey small', }, 
        { code: 'Key_Alt_Left', name: 'Alt', shiftName: 'Alt', class: 'longkey small', }, 
        { code: 'Key_Space', name: ' ', shiftName: ' ', class: 'longkey space', }, 
        { code: 'Key_Alt_Right', name: 'Alt', shiftName: 'Alt', class: 'longkey small', }, 
        { code: 'Key_Left', name: '◄', shiftName: '◄', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Down', name: '▼', shiftName: '▼', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Right', name: '►', shiftName: '►', class: 'shortkey',  property: 'printable', }, 
        { code: 'Key_Ctrl_Right', name: 'Ctrl', shiftName: 'Ctrl', class: 'longkey small', }, 
    ],
];

export default enLang;