const ruLang = [
  [
      { code: 'Key_Backtick', key: 'ё', shiftKey: 'Ё', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_1', key: '1', shiftKey: '!', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_2', key: '2', shiftKey: '\"', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_3', key: '3', shiftKey: '№', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_4', key: '4', shiftKey: ';', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_5', key: '5', shiftKey: '%', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_6', key: '6', shiftKey: ':', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_7', key: '7', shiftKey: '?', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_8', key: '8', shiftKey: '*', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_9', key: '9', shiftKey: '(', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_0', key: '0', shiftKey: ')', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Minus', key: '-', shiftKey: '_', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Equal', key: '=', shiftKey: '=', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Backspace', key: 'Backspace', shiftKey: 'Backspace', class: 'longkey large', }, 
  ],
  [
      { code: 'Key_Tab', key: 'Tab', shiftKey: 'Tab', class: 'longkey small', }, 
      { code: 'Key_Q', key: 'й', shiftKey: 'Й', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_W', key: 'ц', shiftKey: 'Ц', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_E', key: 'у', shiftKey: 'У', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_R', key: 'к', shiftKey: 'К', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_T', key: 'е', shiftKey: 'Е', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Y', key: 'н', shiftKey: 'Н', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_U', key: 'г', shiftKey: 'Г', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_I', key: 'ш', shiftKey: 'Ш', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_O', key: 'щ', shiftKey: 'Щ', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_P', key: 'з', shiftKey: 'З', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Bracket_Left', key: 'х', shiftKey: 'Х', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Bracket_Right', key: 'ъ', shiftKey: 'Ъ', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Backslash', key: '\\', shiftKey: '/', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Delete', key: 'Del', shiftKey: 'Del', class: 'longkey small', },
  ],
  [
      { code: 'Key_Caps', key: 'Caps', shiftKey: 'Caps', class: 'longkey small', }, 
      { code: 'Key_A', key: 'ф', shiftKey: 'Ф', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_S', key: 'ы', shiftKey: 'Ы', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_D', key: 'в', shiftKey: 'В', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_F', key: 'а', shiftKey: 'А', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_G', key: 'п', shiftKey: 'П', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_H', key: 'р', shiftKey: 'Р', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_J', key: 'о', shiftKey: 'О', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_K', key: 'л', shiftKey: 'Л', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_L', key: 'д', shiftKey: 'Д', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Semicolon', key: 'ж', shiftKey: 'Ж', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Quote', key: 'э', shiftKey: 'Э', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Enter', key: 'Enter', shiftKey: 'Enter', class: 'longkey large', },
  ],
  [
      { code: 'Key_Shift_Left', key: 'Shift', shiftKey: 'Shift', class: 'longkey medium', }, 
      { code: 'Key_Z', key: 'я', shiftKey: 'Я', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_X', key: 'ч', shiftKey: 'Ч', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_C', key: 'с', shiftKey: 'С', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_V', key: 'м', shiftKey: 'М', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_B', key: 'и', shiftKey: 'И', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_N', key: 'т', shiftKey: 'Т', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_M', key: 'ь', shiftKey: 'Ь', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Comma', key: 'б', shiftKey: 'Б', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Dot', key: 'ю', shiftKey: 'Ю', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Slash', key: '.', shiftKey: ',', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Up', key: '▲', shiftKey: '▲', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Shift_Right', key: 'Shift', shiftKey: 'Shift', class: 'longkey medium', }, 
  ],
  [
      { code: 'Key_Ctrl_Left', key: 'Ctrl', shiftKey: 'Ctrl', class: 'longkey small', }, 
      { code: 'Key_Win', key: 'Win', shiftKey: 'Win', class: 'longkey small', }, 
      { code: 'Key_Alt_Left', key: 'Alt', shiftKey: 'Alt', class: 'longkey small', }, 
      { code: 'Key_Space', key: ' ', shiftKey: ' ', class: 'longkey space', }, 
      { code: 'Key_Alt_Right', key: 'Alt', shiftKey: 'Alt', class: 'longkey small', }, 
      { code: 'Key_Left', key: '◄', shiftKey: '◄', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Down', key: '▼', shiftKey: '▼', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Right', key: '►', shiftKey: '►', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Ctrl_Right', key: 'Ctrl', shiftKey: 'Ctrl', class: 'longkey small', }, 
  ],
];

export default ruLang;