const ruLang = [
  [
      { code: 'Key_Backtick', name: 'ё', shiftName: 'Ё', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_1', name: '1', shiftName: '!', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_2', name: '2', shiftName: '\"', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_3', name: '3', shiftName: '№', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_4', name: '4', shiftName: ';', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_5', name: '5', shiftName: '%', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_6', name: '6', shiftName: ':', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_7', name: '7', shiftName: '?', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_8', name: '8', shiftName: '*', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_9', name: '9', shiftName: '(', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_0', name: '0', shiftName: ')', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Minus', name: '-', shiftName: '_', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Equal', name: '=', shiftName: '=', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Backspace', name: 'Backspace', shiftName: 'Backspace', class: 'longkey large', }, 
  ],
  [
      { code: 'Key_Tab', name: 'Tab', shiftName: 'Tab', class: 'longkey small', }, 
      { code: 'Key_Q', name: 'й', shiftName: 'Й', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_W', name: 'ц', shiftName: 'Ц', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_E', name: 'у', shiftName: 'У', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_R', name: 'к', shiftName: 'К', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_T', name: 'е', shiftName: 'Е', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Y', name: 'н', shiftName: 'Н', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_U', name: 'г', shiftName: 'Г', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_I', name: 'ш', shiftName: 'Ш', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_O', name: 'щ', shiftName: 'Щ', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_P', name: 'з', shiftName: 'З', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Bracket_Left', name: 'х', shiftName: 'Х', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Bracket_Right', name: 'ъ', shiftName: 'Ъ', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Backslash', name: '\\', shiftName: '/', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Delete', name: 'Del', shiftName: 'Del', class: 'longkey small', },
  ],
  [
      { code: 'Key_Caps', name: 'Caps', shiftName: 'Caps', class: 'longkey small', }, 
      { code: 'Key_A', name: 'ф', shiftName: 'Ф', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_S', name: 'ы', shiftName: 'Ы', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_D', name: 'в', shiftName: 'В', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_F', name: 'а', shiftName: 'А', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_G', name: 'п', shiftName: 'П', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_H', name: 'р', shiftName: 'Р', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_J', name: 'о', shiftName: 'О', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_K', name: 'л', shiftName: 'Л', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_L', name: 'д', shiftName: 'Д', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Semicolon', name: 'ж', shiftName: 'Ж', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Quote', name: 'э', shiftName: 'Э', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Enter', name: 'Enter', shiftName: 'Enter', class: 'longkey large', },
  ],
  [
      { code: 'Key_Shift_Left', name: 'Shift', shiftName: 'Shift', class: 'longkey medium', }, 
      { code: 'Key_Z', name: 'я', shiftName: 'Я', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_X', name: 'ч', shiftName: 'Ч', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_C', name: 'с', shiftName: 'С', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_V', name: 'м', shiftName: 'М', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_B', name: 'и', shiftName: 'И', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_N', name: 'т', shiftName: 'Т', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_M', name: 'ь', shiftName: 'Ь', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Comma', name: 'б', shiftName: 'Б', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Dot', name: 'ю', shiftName: 'Ю', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Slash', name: '.', shiftName: ',', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Up', name: '▲', shiftName: '▲', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Shift_Right', name: 'Shift', shiftName: 'Shift', class: 'longkey medium', }, 
  ],
  [
      { code: 'Key_Ctrl_Left', name: 'Ctrl', shiftName: 'Ctrl', class: 'longkey small', }, 
      { code: 'Key_Win', name: 'Win', shiftName: 'Win', class: 'longkey small', }, 
      { code: 'Key_Alt_Left', name: 'Alt', shiftName: 'Alt', class: 'longkey small', }, 
      { code: 'Key_Space', name: ' ', shiftName: ' ', class: 'longkey space', }, 
      { code: 'Key_Alt_Right', name: 'Alt', shiftName: 'Alt', class: 'longkey small', }, 
      { code: 'Key_Left', name: '◄', shiftName: '◄', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Down', name: '▼', shiftName: '▼', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Right', name: '►', shiftName: '►', class: 'shortkey',  property: 'printable', }, 
      { code: 'Key_Ctrl_Right', name: 'Ctrl', shiftName: 'Ctrl', class: 'longkey small', }, 
  ],
];

export default ruLang;